https://raw.githubusercontent.com/JUAN-32/ETL-DATA-PIPELINE-25-0095-2022-/refs/heads/main/nootebooks/A_notas.csv

In [ ]:
import pandas as pd

In [ ]:
url="https://raw.githubusercontent.com/JUAN-32/ETL-DATA-PIPELINE-25-0095-2022-/refs/heads/main/nootebooks/A_notas.csv"
df = pd.read_csv(url)
df.head()

  id_nota id_estudiante id_curso nota  periodo
0   N5000         E1102     C204  7.9   I-2025
1   N5001         E1179     C205  8.1   I-2025
2   N5002         E1092     C202  8.6   I-2025
3   N5003         E1014     C211  8.0   I-2025
4   N5004         E1106     C208  7.4  II-2025

In [ ]:
#limpieza de datos
A_notas = df.copy()

A_notas.columns = A_notas.columns.str.strip().str.lower()

for col in A_notas.select_dtypes(include='object').columns:
    A_notas[col] = A_notas[col].astype(str).str.strip()

siniestros = A_notas.replace(r'^\s*$', pd.NA, regex=True)


A_notas['nota'] = A_notas['nota'].replace(['N/A', '0'], pd.NA)
A_notas['id_estudiante'] = A_notas['id_estudiante'].replace(['N/A', '-'], pd.NA)


A_notas['id_curso'] = A_notas['id_curso'].replace(['N/A', '-'], pd.NA)

A_notas['nota'] = A_notas['nota'].replace(['diez', '10'], pd.NA)
A_notas['nota'] = A_notas['nota'].astype(str).str.replace(",", "", regex=False)
A_notas['nota'] = pd.to_numeric(siniestros['nota'], errors='coerce')

In [ ]:
#Separar datos válidos y rechazados
validos = A_notas[
    A_notas['nota'].notna() &
    A_notas['id_curso'].notna() &
      A_notas['periodo'].notna() &
     A_notas['id_estudiante'].notna()
].copy()

rechazados = A_notas[
    A_notas['nota'].isna() |
    A_notas['id_curso'].isna() |
    A_notas['periodo'].isna() |
     A_notas['id_estudiante'].isna()

].copy()

In [ ]:
#Exportar archivos
validos.to_csv("A_notas_curated.csv", index=False)

rechazados.to_csv("A_notas_rejects.csv", index=False)

In [ ]:
#motivo de rechazo
def motivo(row):
    motivos = []

    if pd.isna(row['nota']):
        motivos.append("nota_vacia")

    if pd.isna(row['id_curso']):
        motivos.append("monto_vacio")

    if pd.isna(row['periodo']):
        motivos.append("periodo_vacio")
    if pd.isna(row['id_estudiante']):
        motivos.append("estudiante_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [ ]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_nota        330 non-null    object
 1   id_estudiante  325 non-null    object
 2   id_curso       328 non-null    object
 3   nota           326 non-null    object
 4   periodo        330 non-null    object
dtypes: object(5)
memory usage: 13.0+ KB

id_nota          0
id_estudiante    5
id_curso         2
nota             4
periodo          0
dtype: int64

In [ ]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd



database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"
engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

   ?column?
0         1

In [84]:

validos.to_sql('nota_curated', engine, if_exists='append', index=False)

rechazados.to_sql('nota_rejects', engine, if_exists='append', index=False)

27

In [85]:
pd.read_sql(
    "SELECT * FROM nota_curated LIMIT 10",
    engine
)

  id_nota id_estudiante id_curso  nota  periodo
0   N5000         E1102     C204   7.9   I-2025
1   N5001         E1179     C205   8.1   I-2025
2   N5002         E1092     C202   8.6   I-2025
3   N5003         E1014     C211   8.0   I-2025
4   N5004         E1106     C208   7.4  II-2025
5   N5005         E1071     C204   3.9  II-2025
6   N5006         E1020     C207   5.2  II-2025
7   N5007         E1102     C200   5.8   I-2025
8   N5008         E1121     C204   2.7   I-2025
9   N5009         E1074     C202   6.2   I-2025